{{- range $.Values.models }}
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .name }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: {{ .rewriteTarget }}
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    cert-manager.io/issue-temporary-certificate: "true"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  rules:
    - host: {{ $.Values.host }}
      http:
        paths:
          - path: {{ .path }}
            backend:
              serviceName: {{ .name }}
              servicePort: {{ .port }}
  tls:
  - hosts:
    - {{ .Values.host }}
    secretName: "{{ .name }}-ingress-tls-secret"

{{- end }}
