host: seacorenlp.aisingapore.net

ui:
  name: ui
  port: 8080
  image: asia.gcr.io/infra-public-hosting/seacorenlp/seacorenlp-ui:latest

docs:
  name: docs
  port: 80
  image: asia.gcr.io/infra-public-hosting/seacorenlp/seacorenlp-docs:latest
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"

models:
  seaPOSTagger:
    name: sea-pos-tagger
    port: 8080
    path: /api/sea-pos-tagger/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: asia.gcr.io/infra-public-hosting/seacorenlp/pos-tagger:latest
    resources:
      requests:
        memory: "8Gi"
        cpu: "500m"
  seaNERTagger:
    name: sea-ner-tagger
    port: 8080
    path: /api/sea-ner-tagger/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: asia.gcr.io/infra-public-hosting/seacorenlp/ner-tagger:latest
    resources:
      requests:
        memory: "5Gi"
        cpu: "600m"
  seaDepParser:
    name: sea-dep-parser
    port: 8080
    path: /api/sea-dep-parser/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: asia.gcr.io/infra-public-hosting/seacorenlp/dep-parser:latest
    resources:
      requests:
        memory: "8Gi"
        cpu: "700m"
  seaConstParser:
    name: sea-const-parser
    port: 8080
    path: /api/sea-const-parser/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: asia.gcr.io/infra-public-hosting/seacorenlp/const-parser:latest
    resources:
      requests:
        memory: "4Gi"
        cpu: "700m"
