host: seacorenlp.vbrani.aisingapore.net

ui:
  name: ui
  port: 8080
  image: registry.aisingapore.net/sg-nlp/sea-core-nlp-ui:latest

docs:
  name: docs
  port: 80
  image: registry.aisingapore.net/sea-core-nlp/seacorenlp-docs:latest

models:
  seaPOSTagger:
    name: sea-pos-tagger
    port: 8080
    path: /api/sea-pos-tagger/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: registry.aisingapore.net/sea-core-nlp/sea-pos-tagger-api:latest
  seaNERTagger:
    name: sea-ner-tagger
    port: 8080
    path: /api/sea-ner-tagger/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: registry.aisingapore.net/sea-core-nlp/sea-ner-tagger-api:latest
  seaDepParser:
    name: sea-dep-parser
    port: 8080
    path: /api/sea-dep-parser/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: registry.aisingapore.net/sea-core-nlp/sea-dep-parser-api:latest
  seaConstParser:
    name: sea-const-parser
    port: 8080
    path: /api/sea-const-parser/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: registry.aisingapore.net/sea-core-nlp/sea-const-parser-api:latest
